name: gtrace
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go: [1.17.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Go Env
      run: |
        go env

    - name: Build
      run: |
        go install ./internal/cmd/gtrace

    - name: Clean and re-generate *_gtrace.go files
      run: |
        cd ./trace && rm -f *_gtrace.go && go generate

    - name: Check generation
      run: |
        if [[ $(git status --porcelain) -ne 0 ]]; then
          echo "code-generation not compatible with gtrace output";
          exit 1;
        fi
